### PR TITLE
Handle shutdown requests

### LINKED ISSUE #400: The LSP server doesn't reply to shutdown
I'm trying to use taplo with eglot in emacs. When I shutdown the LSP server (with eglot-shutdown), it doesn't reply. Here's the relevant log:

```
[client-request] (id:3) Sat Apr 29 13:29:57 2023:
(:jsonrpc "2.0" :id 3 :method "shutdown" :params nil)
```

The LSP server doesn't reply to this request. I'm able to fix the problem with #401.

### PR DESCRIPTION
**Pull request by ia0**
Fixes #400

### CODE REVIEW

**Comment by irevoire** [comment]
Shouldn’t we match the shutdown request here as well to drop the input/output?
```rust
if msg.method.as_ref().map(|m| m == "exit").unwrap_or(false) {
                                    drop(output);
                                    drop(input);
                                    break;
                                }
```

**Comment by ia0** [comment]
> Genuine question; shouldn’t we match the shutdown request here as well to drop the input/output?

I don't know about the input/output dropping but we definitely don't want to exit the loop. We want to execute the `handle_request` method.

**Comment by Philipp-M** [comment]
Duplicate of #354

**Comment by ia0** [comment]
> Duplicate of #354

Very good point! How did I miss that one? I'm going to contribute there and closing this.

**Pull request closed without merging**
