### PR TITLE
bump versions

### LINKED ISSUE #386: Chore: Upgrade `toml` dep to at least `0.6.0` for full TOML 1.0 compliance
https://github.com/toml-rs/toml/blob/74b57e74bf950a3e8962ec95df992dd29ecc8c92/crates/toml/CHANGELOG.md

`toml@0.6.0` brought full TOMLv1 compliance, it would be great to upgrade the project to use this version.

Currently the latest version is at 0.7.3, which brings additional bugfixes

### LINKED ISSUE #403: Looking for maintainers
I had many plans with this project but it has become apparent that I currently cannot seem to dedicate any time to OSS and it's not clear when this will change.

I'm looking for maintainers to take over this repo, mainly to triage PRs and publish new versions.

### LINKED ISSUE #473: Release a new version
#449 and #462 are fixing important issues and need to be released. There are other minor changes since the last release.

Before releasing, we should also bump `json_value_merge` to 2.0.0 (and update the code accordingly) because 1.2.0 was a breaking change.

### LINKED ISSUE #480: NPM package is not up-to-date
On NPM: https://www.npmjs.com/package/@taplo/lib, the latest version is `0.4.0-alpha.2`, which is published one year ago;
On crates.io: https://crates.io/crates/taplo, the latest version is `0.12.1`, which is published 3 months ago.

### PR DESCRIPTION
**Pull request by panekj**
close #386
close #403
close #473
close #480

### CODE REVIEW

**Comment by JounQin** [comment]
@panekj So this PR still doesn't receive updates after https://github.com/tamasfe/taplo/issues/403#issuecomment-1829128550.

**Comment by panekj** [comment]
> @panekj So this PR still doesn't receive updates after [#403 (comment)](https://github.com/tamasfe/taplo/issues/403#issuecomment-1829128550).

Comments in issues actually don't decrease work I have so no, there has been no update.

**Comment by panekj** [comment]
What is mainly missing is changelog to collect and write up.

**Comment by JounQin** [comment]
> What is mainly missing is changelog to collect and write up.

@panekj They should be definitely managed by tools like [changesets](https://github.com/changesets/changesets) FYI, manually maintaining such verbose jobs is boring and tiring IMO.

**Comment by flying-sheep** [comment]
I personally like https://release-plz.ieni.dev/

It works like this:
1. create a changelog file in the supported format
2. add a workflow that runs the GitHub action
3. whenever you make commits, the action creates or updates a PR with the changelog
4. when you merge the PR, a new release is tagged and uploaded to crates.io

**Comment by JounQin** [comment]
@flying-sheep Where are the changelog contents from?

**Comment by JounQin** [comment]
> Release-plz updates your changelogs with [git-cliff](https://git-cliff.org/) using [Keep a changelog](https://keepachangelog.com/en/1.0.0/) format by default.

OK, it's still commit message based, what means the changelog can not be changed after committed. Not flexible as `changesets`.

**Comment by flying-sheep** [comment]
Whatever works best for you!

Just FYI: with release-plz, you can change the changelog in the PR before merging. The changelog/versions it autogenerates are not just message based, it also analyzes your code and figures out if your API changes classify as breaking or not.

But in the end, you are in control. Check out this example for a release PR: https://github.com/MarcoIeni/release-plz/pull/1170

**Comment by JounQin** [comment]
```sh
# taplo/js/cli
yarn build
```

```log
warning: unused import: `taplo_common::environment::Environment`
   --> src/lib.rs:216:9
    |
216 |     use taplo_common::environment::Environment;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

warning: `taplo-wasm` (lib) generated 1 warning (run `cargo fix --lib -p taplo-wasm` to apply 1 suggestion)
    Finished dev [unoptimized] target(s) in 1.48s
Downloading wasm-bindgen version 0.2.82
[!] (plugin rpt2) Error: Could not load /Users/JounQin/Workspaces/GitHub/taplo/crates/taplo-wasm/Cargo.toml (imported by src/cli.ts): Rust compilation failed
```

It seems that I'm blocked by `@wasm-tool/rollup-plugin-rust`, does anyone has any idea?

cc @tamasfe @ia0 @panekj 

Maybe we should migrate to https://github.com/napi-rs/napi-rs ASAP.

**Comment by JounQin** [comment]
@tamasfe 

Can we change the merge option from `merge` to `squash` or `rebase`?

image

**Comment by JounQin** [comment]
I'll merge this PR as-is soon later.

**Review by tamasfe — APPROVED** [review]

**Comment by tamasfe** [comment]
> @tamasfe
> 
> Can we change the merge option from `merge` to `squash` or `rebase` (disable adding a new merge commit option)?
> image

Sure, squashing by default is a bad idea, but I prefer rebasing as well.

**Comment by JounQin** [comment]
@tamasfe Merging with a new commit can be disabled in GitHub settings.

**Comment by JounQin** [comment]
@tamasfe 

https://crates.io/crates/taplo-cli

It seems the crates were not released correctly, can you help to release manually or give me the release permission so I can do it even after?

**Comment by tamasfe** [comment]
Weird, the tags seem to be correct to me yet no CI started. I've sent invites both on crates and npm.

I'll figure out how to grant permission to the vscode extension at microsoft and openvsx later.

**Comment by JounQin** [comment]
@tamasfe Thanks for your trust, I've published all crates and npm packages successfully except https://crates.io/crates/lsp-async-stub, although it is not in emergency situation.

**Comment by JounQin** [comment]
@tamasfe Would you mind to add me as owner for https://crates.io/crates/lsp-async-stub at the same time when you're free? So that I can help to publish a new version for it.

**Pull request merged**
