### PR TITLE
feat(ci): build additional architectures

### LINKED ISSUE #90: Provide a binary release built on musl-c for taplo-cli
Right now to use `taplo-cli` I have to get cargo first and then build `taplo-cli`. Runime performance-wise it's a good idea but when it comes to an ease of setup it's not that good. Lately I started working more with Docker containers and GH Actions with a variety of Linux distributions on it and using taplo there to lint my tol files is quite problematic.
What I'd like to see is a pre-built release of `taplo-cli` I can download from [this page](https://github.com/tamasfe/taplo/releases). I think `x86_64-unknown-linux-musl` target will suite this purpose best. 
I see there is a GitHub Action to automate such process - https://github.com/marketplace/actions/automatic-releases

Would you be interested in such a feature?

### LINKED ISSUE #232: Build on Windows
The CLI does not have a documented way to build on Windows and I don't have access to a Windows machine right now, but this is definitely a must-have.

### LINKED ISSUE #289: [Feature Request] Pre-built binary for aarch64
Thanks a lot for great language-server!
I currently use computer which is `linux` and `aarch64` ( `arm64` ), and install taplo from cargo.
I want to download pre-built binary from GitHub Release.

### PR DESCRIPTION
**Pull request by panekj**
- build taplo and taplo-full for all platforms
- add x86/aarch64

Fixes #90 
Fixes #289 
Fixes #232

### CODE REVIEW

**Comment by tamasfe** [comment]
This looks great, thanks!

Is this ready to be merged?

**Comment by panekj** [comment]
> Is this ready to be merged?

It is now
https://github.com/panekj/taplo/actions/runs/3228681372
https://github.com/panekj/taplo/releases/tag/0.7.1

**Comment by tamasfe** [comment]
Awesome, thanks!

**Comment by panekj** [comment]
Feel free to ping me in case of any issues with workflow

**Pull request merged**
