### PR TITLE
Adapt regex from poetry project

### PR DESCRIPTION
**Pull request by SanderBeekhuis**
This PR solves #360  and  #384 

We adept the Regex in use in the poetry project  https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/packages/package.py in order to be just as permissive as the Poetry project, for which we are validating.

-----
This PR is our first contribution. We are very open to suggestions and improvements.

This PR was a group effort by Ordina Pythoneers, they would like to thank Ordina for the time to do this.

@SanderBeekhuis 
@RoelAdriaans
@Coen-Smulders

### CODE REVIEW

**Comment by panekj** [comment]
I think it has to be fixed in SchemaStore since that's the primary source for schemas used
https://github.com/SchemaStore/schemastore/blob/94ae74640898dcdb162a68a963b6fb6a3a29ef9e/src/schemas/json/pyproject.json#L39

**Comment by SanderBeekhuis** [comment]
@panekj (or somebody else).

It has been fixed upstream in https://github.com/SchemaStore/schemastore/pull/3209  what will  be the process of landing this fix in this extension?

**Comment by ia0** [comment]
I don't think there's anything to do. The catalog and (if I'm not mistaken) the schemas are downloaded at runtime. So as soon as they publish the new version (which I think is quite fast and seems to already be the case now because the issues are fixed for me), then you should see the fix (possibly restarting your editor). I don't know if schemas are cached though. Please ping here if you it's not fixed.

**Comment by SanderBeekhuis** [comment]
@ia0 You are right. It also works on my machine.

**Pull request closed without merging**
