### PR TITLE
Fix comments with brackets

### LINKED ISSUE #455: Formatter destoys data
Sorry for the dramatic title. `taplo fmt` does this to my array:

```diff
 ignore = [
   # __magic__ methods are are often self-explanatory, allow missing docstrings
   "D105",
-  # first line should end with a period [Bug: doesn't work with single-line docstrings]
-  "D400",
+  # first line should end with a period [Bug: doesn't work with single-line docstrings]  "D400",
   # First line should be in imperative mood; try rephrasing
   "D401",
 ]
```

This removes the `"D400"` entry from it

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #455

### CODE REVIEW

**Comment by ia0** [comment]
There's actually an easy way to fix this, but I don't know if there are other consequences.

Just remove this `if` and always execute its content: https://github.com/tamasfe/taplo/blob/5bd96253075e42dfbebe9c441611c36412c3221a/crates/taplo/src/formatter/mod.rs#L1109-L1112

This `if` looks like a hack to detect if an array just finished, but the closing bracket could be part of a comment. I don't know the situations when this `if` is false. It would be nice to figure out and add a test. If it can never happen then we're good. If it can happen, then we need to introduce a new variable to remember if we just closed a bracket outside a comment (probably 3 more lines of code and a bit hacky).

**Comment by panekj** [comment]
Could you also add test for your issue similar to
https://github.com/tamasfe/taplo/blob/cb156c30c1072b40ed66cd1defe83975aa4ce1f1/crates/taplo/src/tests/formatter.rs#L161-L181

**Review by ia0 — APPROVED** [review]
I tried to play around to find when the `if` does not trigger but couldn't. So I agree we can move forward and wait until someone comes up with an example. In the absence of a test breaking, I think we can say that this is not an important feature that is being removed.

I don't think the `[` case is similar, because it can't come after a comment. The only thing that can follow a comment is a newline by definition of a comment. So only the occurrence in the NEWLINE case is actually problematic.

**Comment by flying-sheep** [comment]
could we get a release with this?

**Comment by ia0** [comment]
> could we get a release with this?

Ideally, I'd like #434 to get fixed before releasing. It's an important blocker for releasing to VS Code. Feel free to take a look at it if you're familiar with VS Code. PRs are welcome. Thanks!

**Comment by flying-sheep** [comment]
I fixed that one, see #462

**Review by panekj — APPROVED** [review]

**Pull request merged**
